### ISSUE TITLE
ライセンスについて

### ISSUE THREAD

**Issue by dadenCKEP** [hakkafox/VrcVideoUrlDispenser#1]
このコンポーネントを利用・アップデートを考えているのですが、現在の状態では、「[No License](https://choosealicense.com/no-permission/)」となり、それらの許可が明示されてない状態だと思われます。意図的な保護でないのであれば、何らかのOSSライセンスを付与していただけないでしょうか。

具体的な手順の例としては以下のような例になります。
https://qiita.com/medi-y-sato/items/c3d5c357ab020290dccc

よろしくお願いします。

**Comment by hakkafox** [comment]
まずは返信が遅くなった事をお詫びさせてください。

このリポジトリについてですが、商用・非商用問わず、煮るなり焼くなり好きにしてください。
なので、Unlicenseとしてライセンスを付与いたしました。

近い将来にこのリポジトリを削除しようと思っていたので、アップデートを考慮に入れていただける事を嬉しく思います。

**Comment by dadenCKEP** [comment]
ありがとうございます。使わせていただきます。
